# CLI
brew "git"
brew "stow"
brew "neovim"
brew "tree-sitter"
brew "typescript"
brew "starship"
brew "lazygit"
brew "ripgrep"
brew "fd"
brew "fzf"
brew "fzf-tab"
brew "bat"
brew "jq"
brew "zoxide"
brew "eza"
brew "kubectl"
brew "awscli"
brew "lazydocker"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "mas"

# Terminal + multiplexer
cask "ghostty"
brew "zellij"

# Fonts
cask "font-jetbrains-mono-nerd-font"

# Runtime managers
brew "mise"
brew "rustup-init"

# Apps (optional)
cask "raycast"
cask "zed"
cask "obsidian"
cask "brave-browser"
cask "docker-desktop"
cask "codex"
cask "claude-code"
cask "gcloud-cli"
